version: "2.3"
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./setup/default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/php
    ports:
      - "8080:80"
    networks:
      - mynet
  php:
    build:
      context: .
      dockerfile: Phpdockerfile
    networks:
      - mynet
  database:
    container_name: maria
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: n130177
      MARIADB_DATABASE: nikosdrosakisgr
      MARIADB_USER: dros
      MARIADB_PASSWORD: n130177
    ports:
      - "9906:3306"
    volumes:
      - ./setup/nikosdrosakisgr.sql:/docker-entrypoint-initdb.d/init.sql
      - mydb:/var/lib/mysql
    networks:
      - mynet
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    hostname: localhost
    ports:
      - "8021:80"
    links:
      - database
    environment:
      - PMA_HOST=database
      - PMA_CONTROLUSER=dros
      - PMA_CONTROLPASS=n130177
    networks:
      - mynet
networks:
  mynet:
volumes:
  mydb: